/**
 * Auth-SSO 错误码定义
 * @module @auth-sso/contracts/errors
 */

// 错误码前缀
const ERROR_PREFIX = 'AUTH_SSO';

// 通用错误码 (1xxx)
export const COMMON_ERRORS = {
  UNKNOWN_ERROR: `${ERROR_PREFIX}_1000`,
  INVALID_REQUEST: `${ERROR_PREFIX}_1001`,
  UNAUTHORIZED: `${ERROR_PREFIX}_1002`,
  FORBIDDEN: `${ERROR_PREFIX}_1003`,
  NOT_FOUND: `${ERROR_PREFIX}_1004`,
  VALIDATION_ERROR: `${ERROR_PREFIX}_1005`,
  INTERNAL_ERROR: `${ERROR_PREFIX}_1006`,
} as const;

// 认证错误码 (2xxx)
export const AUTH_ERRORS = {
  // 登录相关
  LOGIN_FAILED: `${ERROR_PREFIX}_2001`,
  INVALID_CREDENTIALS: `${ERROR_PREFIX}_2002`,
  ACCOUNT_DISABLED: `${ERROR_PREFIX}_2003`,
  ACCOUNT_LOCKED: `${ERROR_PREFIX}_2004`,
  ACCOUNT_NOT_FOUND: `${ERROR_PREFIX}_2005`,

  // Session 相关
  SESSION_EXPIRED: `${ERROR_PREFIX}_2010`,
  SESSION_INVALID: `${ERROR_PREFIX}_2011`,
  SESSION_NOT_FOUND: `${ERROR_PREFIX}_2012`,

  // Token 相关
  TOKEN_EXPIRED: `${ERROR_PREFIX}_2020`,
  TOKEN_INVALID: `${ERROR_PREFIX}_2021`,
  TOKEN_REVOKED: `${ERROR_PREFIX}_2022`,
  REFRESH_TOKEN_EXPIRED: `${ERROR_PREFIX}_2023`,
  REFRESH_TOKEN_INVALID: `${ERROR_PREFIX}_2024`,

  // OIDC 相关
  INVALID_STATE: `${ERROR_PREFIX}_2030`,
  INVALID_NONCE: `${ERROR_PREFIX}_2031`,
  INVALID_CODE: `${ERROR_PREFIX}_2032`,
  INVALID_REDIRECT_URI: `${ERROR_PREFIX}_2033`,
  PKCE_VERIFICATION_FAILED: `${ERROR_PREFIX}_2034`,
  INVALID_CLIENT: `${ERROR_PREFIX}_2035`,
  UNSUPPORTED_GRANT_TYPE: `${ERROR_PREFIX}_2036`,
} as const;

// 用户管理错误码 (3xxx)
export const USER_ERRORS = {
  USER_NOT_FOUND: `${ERROR_PREFIX}_3001`,
  USER_ALREADY_EXISTS: `${ERROR_PREFIX}_3002`,
  USERNAME_ALREADY_EXISTS: `${ERROR_PREFIX}_3003`,
  EMAIL_ALREADY_EXISTS: `${ERROR_PREFIX}_3004`,
  MOBILE_ALREADY_EXISTS: `${ERROR_PREFIX}_3005`,
  INVALID_PASSWORD: `${ERROR_PREFIX}_3006`,
  PASSWORD_TOO_WEAK: `${ERROR_PREFIX}_3007`,
  CANNOT_DELETE_SELF: `${ERROR_PREFIX}_3008`,
  CANNOT_DISABLE_SELF: `${ERROR_PREFIX}_3009`,
} as const;

// 部门管理错误码 (4xxx)
export const DEPARTMENT_ERRORS = {
  DEPARTMENT_NOT_FOUND: `${ERROR_PREFIX}_4001`,
  DEPARTMENT_ALREADY_EXISTS: `${ERROR_PREFIX}_4002`,
  DEPARTMENT_HAS_CHILDREN: `${ERROR_PREFIX}_4003`,
  DEPARTMENT_HAS_USERS: `${ERROR_PREFIX}_4004`,
  CANNOT_DELETE_ROOT: `${ERROR_PREFIX}_4005`,
  CANNOT_MOVE_TO_CHILD: `${ERROR_PREFIX}_4006`,
} as const;

// 角色管理错误码 (5xxx)
export const ROLE_ERRORS = {
  ROLE_NOT_FOUND: `${ERROR_PREFIX}_5001`,
  ROLE_ALREADY_EXISTS: `${ERROR_PREFIX}_5002`,
  CANNOT_DELETE_SYSTEM_ROLE: `${ERROR_PREFIX}_5003`,
  CANNOT_MODIFY_SYSTEM_ROLE: `${ERROR_PREFIX}_5004`,
} as const;

// 权限管理错误码 (6xxx)
export const PERMISSION_ERRORS = {
  PERMISSION_NOT_FOUND: `${ERROR_PREFIX}_6001`,
  PERMISSION_ALREADY_EXISTS: `${ERROR_PREFIX}_6002`,
  INSUFFICIENT_PERMISSIONS: `${ERROR_PREFIX}_6003`,
} as const;

// Client 管理错误码 (7xxx)
export const CLIENT_ERRORS = {
  CLIENT_NOT_FOUND: `${ERROR_PREFIX}_7001`,
  CLIENT_ALREADY_EXISTS: `${ERROR_PREFIX}_7002`,
  CLIENT_DISABLED: `${ERROR_PREFIX}_7003`,
  INVALID_REDIRECT_URI: `${ERROR_PREFIX}_7004`,
  SECRET_ROTATION_FAILED: `${ERROR_PREFIX}_7005`,
} as const;

// 错误码到消息的映射
export const ERROR_MESSAGES: Record<string, string> = {
  // 通用
  [COMMON_ERRORS.UNKNOWN_ERROR]: '未知错误',
  [COMMON_ERRORS.INVALID_REQUEST]: '无效请求',
  [COMMON_ERRORS.UNAUTHORIZED]: '未授权',
  [COMMON_ERRORS.FORBIDDEN]: '无权限',
  [COMMON_ERRORS.NOT_FOUND]: '资源不存在',
  [COMMON_ERRORS.VALIDATION_ERROR]: '参数校验失败',
  [COMMON_ERRORS.INTERNAL_ERROR]: '内部错误',

  // 认证
  [AUTH_ERRORS.LOGIN_FAILED]: '登录失败',
  [AUTH_ERRORS.INVALID_CREDENTIALS]: '用户名或密码错误',
  [AUTH_ERRORS.ACCOUNT_DISABLED]: '账号已禁用',
  [AUTH_ERRORS.ACCOUNT_LOCKED]: '账号已锁定',
  [AUTH_ERRORS.ACCOUNT_NOT_FOUND]: '账号不存在',
  [AUTH_ERRORS.SESSION_EXPIRED]: '会话已过期',
  [AUTH_ERRORS.SESSION_INVALID]: '会话无效',
  [AUTH_ERRORS.SESSION_NOT_FOUND]: '会话不存在',
  [AUTH_ERRORS.TOKEN_EXPIRED]: 'Token 已过期',
  [AUTH_ERRORS.TOKEN_INVALID]: 'Token 无效',
  [AUTH_ERRORS.TOKEN_REVOKED]: 'Token 已撤销',
  [AUTH_ERRORS.REFRESH_TOKEN_EXPIRED]: 'Refresh Token 已过期',
  [AUTH_ERRORS.REFRESH_TOKEN_INVALID]: 'Refresh Token 无效',
  [AUTH_ERRORS.INVALID_STATE]: '无效的 state 参数',
  [AUTH_ERRORS.INVALID_NONCE]: '无效的 nonce 参数',
  [AUTH_ERRORS.INVALID_CODE]: '无效的授权码',
  [AUTH_ERRORS.INVALID_REDIRECT_URI]: '无效的回调地址',
  [AUTH_ERRORS.PKCE_VERIFICATION_FAILED]: 'PKCE 验证失败',
  [AUTH_ERRORS.INVALID_CLIENT]: '无效的 Client',
  [AUTH_ERRORS.UNSUPPORTED_GRANT_TYPE]: '不支持的授权类型',

  // 用户
  [USER_ERRORS.USER_NOT_FOUND]: '用户不存在',
  [USER_ERRORS.USER_ALREADY_EXISTS]: '用户已存在',
  [USER_ERRORS.USERNAME_ALREADY_EXISTS]: '用户名已存在',
  [USER_ERRORS.EMAIL_ALREADY_EXISTS]: '邮箱已存在',
  [USER_ERRORS.MOBILE_ALREADY_EXISTS]: '手机号已存在',
  [USER_ERRORS.INVALID_PASSWORD]: '密码错误',
  [USER_ERRORS.PASSWORD_TOO_WEAK]: '密码强度不足',
  [USER_ERRORS.CANNOT_DELETE_SELF]: '不能删除自己',
  [USER_ERRORS.CANNOT_DISABLE_SELF]: '不能禁用自己',

  // 部门
  [DEPARTMENT_ERRORS.DEPARTMENT_NOT_FOUND]: '部门不存在',
  [DEPARTMENT_ERRORS.DEPARTMENT_ALREADY_EXISTS]: '部门已存在',
  [DEPARTMENT_ERRORS.DEPARTMENT_HAS_CHILDREN]: '部门下有子部门',
  [DEPARTMENT_ERRORS.DEPARTMENT_HAS_USERS]: '部门下有用户',
  [DEPARTMENT_ERRORS.CANNOT_DELETE_ROOT]: '不能删除根部门',
  [DEPARTMENT_ERRORS.CANNOT_MOVE_TO_CHILD]: '不能移动到子部门',

  // 角色
  [ROLE_ERRORS.ROLE_NOT_FOUND]: '角色不存在',
  [ROLE_ERRORS.ROLE_ALREADY_EXISTS]: '角色已存在',
  [ROLE_ERRORS.CANNOT_DELETE_SYSTEM_ROLE]: '不能删除系统角色',
  [ROLE_ERRORS.CANNOT_MODIFY_SYSTEM_ROLE]: '不能修改系统角色',

  // 权限
  [PERMISSION_ERRORS.PERMISSION_NOT_FOUND]: '权限不存在',
  [PERMISSION_ERRORS.PERMISSION_ALREADY_EXISTS]: '权限已存在',
  [PERMISSION_ERRORS.INSUFFICIENT_PERMISSIONS]: '权限不足',

  // Client
  [CLIENT_ERRORS.CLIENT_NOT_FOUND]: 'Client 不存在',
  [CLIENT_ERRORS.CLIENT_ALREADY_EXISTS]: 'Client 已存在',
  [CLIENT_ERRORS.CLIENT_DISABLED]: 'Client 已禁用',
  [CLIENT_ERRORS.INVALID_REDIRECT_URI]: '无效的回调地址',
  [CLIENT_ERRORS.SECRET_ROTATION_FAILED]: 'Secret 轮换失败',
};

/**
 * 获取错误消息
 */
export function getErrorMessage(code: string): string {
  return ERROR_MESSAGES[code] || '未知错误';
}